Print KubeLinter version in plaintext lint report
so that it is easier to spot reports made with old checks.

Here's how it looks

```
KubeLinter 0.1.6-23-geb281ddbe6-dirty

<standard input>: (object: stackrox/scanner-6bfc996879-qcqcm /v1, Kind=Pod) serviceAccount is specified (scanner), but this field is deprecated; use serviceAccountName instead (check: deprecated-service-account-field, remediation: Use the serviceAccountName field instead of the serviceAccount field.)

<standard input>: (object: stackrox/scanner-6bfc996879-qcqcm /v1, Kind=Pod) container "scanner" does not have a read-only root file system (check: no-read-only-root-fs, remediation: Set readOnlyRootFilesystem to true in your container's securityContext.)

<standard input>: (object: stackrox/scanner-6bfc996879-qcqcm /v1, Kind=Pod) serviceAccount "scanner" not found (check: non-existent-service-account, remediation: Make sure to create the service account, or to refer to an existing service account.)

Error: found 3 lint errors
```